name: Build Windows

on:
  workflow_dispatch: # 允许你手动点击按钮触发
  push:
    branches:
      - '0.10' 

jobs:
  deploy:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Clone
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install .
        pip install pyinstaller

    - name: PyInstaller build
      run: |
        python -m PyInstaller -y --distpath ./installer/dist installer/Amulet.spec

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Amulet-Windows-Build
        path: ./installer/
